"""initial complete schema

Revision ID: 6351e60135f1
Revises: None
Create Date: 2026-07-26 07:28:01.033510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6351e60135f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('ambulance_linked', sa.Boolean(), nullable=False),
    sa.Column('ambulance_count', sa.Integer(), nullable=False),
    sa.Column('emergency_capacity', sa.String(length=50), nullable=False),
    sa.Column('total_doctors', sa.Integer(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("emergency_capacity IN ('available', 'limited', 'full')", name='hospital_emergency_capacity_check'),
    sa.CheckConstraint("verification_status IN ('verified', 'pending', 'rejected', 'under_review')", name='hospital_verification_status_check'),
    sa.CheckConstraint('rating >= 0.0 AND rating <= 5.0', name='hospital_rating_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('patient', 'doctor', 'admin')", name='user_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('assistant_conversations',
    sa.Column('conversation_key', sa.String(length=64), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('emergency_risk', sa.String(length=20), nullable=False),
    sa.Column('last_specialist', sa.String(length=150), nullable=True),
    sa.Column('known_symptoms', sa.JSON(), nullable=False),
    sa.Column('asked_questions', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("emergency_risk IN ('normal', 'moderate', 'critical')", name='assistant_conv_risk_check'),
    sa.CheckConstraint("status IN ('active', 'archived')", name='assistant_conv_status_check'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assistant_conv_patient_updated', 'assistant_conversations', ['patient_user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_assistant_conversations_conversation_key'), 'assistant_conversations', ['conversation_key'], unique=True)
    op.create_index(op.f('ix_assistant_conversations_id'), 'assistant_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_conversations_patient_user_id'), 'assistant_conversations', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_assistant_conversations_status'), 'assistant_conversations', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('success', 'failed', 'warning')", name='audit_log_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('sub_specialties', sa.JSON(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('hospital_name', sa.String(length=150), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_patients', sa.Integer(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('next_available', sa.String(length=100), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_date', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("availability IN ('available', 'busy', 'offline', 'on_leave')", name='doctor_availability_check'),
    sa.CheckConstraint("verification_status IN ('verified', 'pending', 'rejected', 'expired', 'under_review')", name='doctor_verification_status_check'),
    sa.CheckConstraint('rating >= 0.0 AND rating <= 5.0', name='doctor_rating_check'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctors_specialty'), 'doctors', ['specialty'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='notification_priority_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('blood_type', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('insurance_provider', sa.String(length=150), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('consent_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("gender IN ('male', 'female', 'other')", name='patient_gender_check'),
    sa.CheckConstraint('health_score >= 0 AND health_score <= 100', name='patient_health_score_check'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='patient_height_check'),
    sa.CheckConstraint('weight IS NULL OR weight > 0', name='patient_weight_check'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_key', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('knowledge_source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'ai')", name='assistant_msg_role_check'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='assistant_msg_confidence_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assistant_msg_conversation', 'assistant_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_assistant_messages_id'), 'assistant_messages', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_messages_message_key'), 'assistant_messages', ['message_key'], unique=False)
    op.create_table('cases',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('patient_gender', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('symptom_summary', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ai_extracted_symptoms', sa.JSON(), nullable=False),
    sa.Column('ai_specialty_recommendation', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('patient_history', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('intake', 'ai_processing', 'routed', 'in_consultation', 'prescribed', 'report_generated', 'completed', 'archived')", name='case_status_check'),
    sa.CheckConstraint("urgency_level IN ('low', 'medium', 'high', 'critical')", name='case_urgency_level_check'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_status_urgency', 'cases', ['status', 'urgency_level'], unique=False)
    op.create_index(op.f('ix_cases_doctor_id'), 'cases', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_patient_id'), 'cases', ['patient_id'], unique=False)
    op.create_index(op.f('ix_cases_specialty'), 'cases', ['specialty'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_urgency_level'), 'cases', ['urgency_level'], unique=False)
    op.create_table('consent_records',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_consent_type'), 'consent_records', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_index(op.f('ix_consent_records_patient_id'), 'consent_records', ['patient_id'], unique=False)
    op.create_table('emergency_requests',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('hospital_name', sa.String(length=150), nullable=True),
    sa.Column('ambulance_dispatched', sa.Boolean(), nullable=False),
    sa.Column('ambulance_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('eta', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'dispatched', 'arrived', 'completed', 'cancelled')", name='emergency_status_check'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_requests_hospital_id'), 'emergency_requests', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_emergency_requests_id'), 'emergency_requests', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_requests_patient_id'), 'emergency_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_requests_status'), 'emergency_requests', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('hospital_name', sa.String(length=150), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'ready', 'reviewed', 'shared', 'pending_review', 'approved', 'rejected', 'needs_revision')", name='report_status_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reports_type'), 'reports', ['type'], unique=False)
    op.create_table('vital_readings',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('normal', 'warning', 'critical')", name='vital_reading_status_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_readings_id'), 'vital_readings', ['id'], unique=False)
    op.create_index(op.f('ix_vital_readings_patient_id'), 'vital_readings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vital_readings_type'), 'vital_readings', ['type'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_name', sa.String(length=200), nullable=False),
    sa.Column('doctor_avatar_url', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('video_call_link', sa.String(length=255), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show')", name='appointment_status_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointment_slot', 'appointments', ['doctor_id', 'date', 'time'], unique=False)
    op.create_index(op.f('ix_appointments_case_id'), 'appointments', ['case_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('intake_sessions',
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('followup_rounds', sa.Integer(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('medical_case_snapshot', sa.JSON(), nullable=True),
    sa.Column('routed_case_id', sa.Uuid(), nullable=True),
    sa.Column('routed_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('collecting', 'awaiting_doctor_selection', 'routed', 'emergency_escalated', 'abandoned')", name='intake_session_status_check'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routed_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routed_doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intake_session_patient_status', 'intake_sessions', ['patient_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_intake_sessions_id'), 'intake_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_patient_user_id'), 'intake_sessions', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_routed_case_id'), 'intake_sessions', ['routed_case_id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_routed_doctor_id'), 'intake_sessions', ['routed_doctor_id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_session_key'), 'intake_sessions', ['session_key'], unique=True)
    op.create_index(op.f('ix_intake_sessions_status'), 'intake_sessions', ['status'], unique=False)
    op.create_table('prescriptions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_name', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ai_parsed', sa.Boolean(), nullable=False),
    sa.Column('ai_parse_confidence', sa.Float(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_date', sa.String(length=100), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'ai_parsing', 'parsed', 'verified', 'active', 'completed', 'cancelled')", name='prescription_status_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_case_id'), 'prescriptions', ['case_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('symptoms',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('mild', 'moderate', 'severe')", name='symptom_severity_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptoms_case_id'), 'symptoms', ['case_id'], unique=False)
    op.create_index(op.f('ix_symptoms_id'), 'symptoms', ['id'], unique=False)
    op.create_table('intake_extracted_entities',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.String(length=20), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('evidence_turn_index', sa.Integer(), nullable=False),
    sa.Column('was_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='intake_entity_confidence_check'),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intake_entity_session_kind', 'intake_extracted_entities', ['session_id', 'kind'], unique=False)
    op.create_index(op.f('ix_intake_extracted_entities_id'), 'intake_extracted_entities', ['id'], unique=False)
    op.create_index(op.f('ix_intake_extracted_entities_kind'), 'intake_extracted_entities', ['kind'], unique=False)
    op.create_index(op.f('ix_intake_extracted_entities_session_id'), 'intake_extracted_entities', ['session_id'], unique=False)
    op.create_table('medications',
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('generic_name', sa.String(length=150), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_times', sa.JSON(), nullable=False),
    sa.Column('taken_doses', sa.Integer(), nullable=False),
    sa.Column('total_doses', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.String(length=100), nullable=False),
    sa.Column('side_effects', sa.JSON(), nullable=False),
    sa.Column('interactions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'taken', 'missed', 'snoozed', 'active')", name='medication_status_check'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_prescription_id'), 'medications', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_prescription_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_intake_extracted_entities_session_id'), table_name='intake_extracted_entities')
    op.drop_index(op.f('ix_intake_extracted_entities_kind'), table_name='intake_extracted_entities')
    op.drop_index(op.f('ix_intake_extracted_entities_id'), table_name='intake_extracted_entities')
    op.drop_index('idx_intake_entity_session_kind', table_name='intake_extracted_entities')
    op.drop_table('intake_extracted_entities')
    op.drop_index(op.f('ix_symptoms_id'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_case_id'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_case_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_intake_sessions_status'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_session_key'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_routed_doctor_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_routed_case_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_patient_user_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_id'), table_name='intake_sessions')
    op.drop_index('idx_intake_session_patient_status', table_name='intake_sessions')
    op.drop_table('intake_sessions')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_case_id'), table_name='appointments')
    op.drop_index('idx_appointment_slot', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_vital_readings_type'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_patient_id'), table_name='vital_readings')
    op.drop_index(op.f('ix_vital_readings_id'), table_name='vital_readings')
    op.drop_table('vital_readings')
    op.drop_index(op.f('ix_reports_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_emergency_requests_status'), table_name='emergency_requests')
    op.drop_index(op.f('ix_emergency_requests_patient_id'), table_name='emergency_requests')
    op.drop_index(op.f('ix_emergency_requests_id'), table_name='emergency_requests')
    op.drop_index(op.f('ix_emergency_requests_hospital_id'), table_name='emergency_requests')
    op.drop_table('emergency_requests')
    op.drop_index(op.f('ix_consent_records_patient_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_consent_type'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_cases_urgency_level'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_specialty'), table_name='cases')
    op.drop_index(op.f('ix_cases_patient_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_doctor_id'), table_name='cases')
    op.drop_index('idx_case_status_urgency', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_assistant_messages_message_key'), table_name='assistant_messages')
    op.drop_index(op.f('ix_assistant_messages_id'), table_name='assistant_messages')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_index('idx_assistant_msg_conversation', table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_doctors_specialty'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assistant_conversations_status'), table_name='assistant_conversations')
    op.drop_index(op.f('ix_assistant_conversations_patient_user_id'), table_name='assistant_conversations')
    op.drop_index(op.f('ix_assistant_conversations_id'), table_name='assistant_conversations')
    op.drop_index(op.f('ix_assistant_conversations_conversation_key'), table_name='assistant_conversations')
    op.drop_index('idx_assistant_conv_patient_updated', table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
