"""unique active appointment slot

Guarantees one live booking per clinician slot at the database level.

`AppointmentService.book_appointment` checks for a conflict before inserting,
but check-then-insert is not safe under concurrency: two requests can both read
the slot as free before either commits. Duplicate rows for the same
doctor/date/time were observed in practice, so the invariant is enforced here
instead of only in application code.

Cancelled, completed, no-show and soft-deleted appointments are excluded, so
releasing a slot makes it bookable again.

Revision ID: cad2efe1fde0
Revises: a1d63f92c704
Create Date: 2026-07-26 21:52:16.561246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad2efe1fde0'
down_revision: Union[str, None] = 'a1d63f92c704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ACTIVE_SLOT_WHERE = (
    "deleted_at IS NULL AND status IN ('scheduled', 'confirmed', 'in_progress')"
)


def _assert_no_existing_duplicates() -> None:
    """
    Refuse to run against data that already violates the invariant.

    Creating the index on such a database fails with an opaque driver error.
    The offending slots are listed instead so an operator can decide which
    booking to keep — this migration must never silently discard one of two
    real patient appointments.
    """
    bind = op.get_bind()
    duplicates = bind.execute(
        sa.text(
            f"""
            SELECT doctor_id, date, time, count(*) AS bookings
            FROM appointments
            WHERE {ACTIVE_SLOT_WHERE}
            GROUP BY doctor_id, date, time
            HAVING count(*) > 1
            ORDER BY bookings DESC
            """
        )
    ).fetchall()

    if duplicates:
        detail = ", ".join(
            f"doctor {row[0]} on {row[1]} at {row[2]} ({row[3]} bookings)"
            for row in duplicates[:10]
        )
        raise RuntimeError(
            f"{len(duplicates)} clinician slot(s) already hold more than one "
            f"active appointment, so a unique slot index cannot be created. "
            f"Cancel or reschedule the surplus bookings first: {detail}"
        )


def upgrade() -> None:
    _assert_no_existing_duplicates()
    op.create_index('uq_appointment_active_slot', 'appointments', ['doctor_id', 'date', 'time'], unique=True, postgresql_where=sa.text(ACTIVE_SLOT_WHERE), sqlite_where=sa.text(ACTIVE_SLOT_WHERE))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointment_active_slot', table_name='appointments', postgresql_where=sa.text("deleted_at IS NULL AND status IN ('scheduled', 'confirmed', 'in_progress')"), sqlite_where=sa.text("deleted_at IS NULL AND status IN ('scheduled', 'confirmed', 'in_progress')"))
    # ### end Alembic commands ###
