import re
import logging
from typing import Tuple, Optional

logger = logging.getLogger("app.ai_core.validators")

MAX_UPLOAD_SIZE_MB = 10
MAX_TEXT_INPUT_LENGTH = 15000

PROMPT_INJECTION_PATTERNS = [
    r"ignore\s+(all\s+)?(previous|above)\s+instructions",
    r"system\s*:\s*",
    r"system\s+prompt",
    r"<\|im_start\|>",
    r"<\|im_end\|>",
    r"forget\s+(all\s+)?(prior|previous)\s+rules",
    r"you\s+are\s+now\s+a\s+DAN",
    r"bypass\s+safety\s+filters",
]

def sanitize_prompt_input(text: str, max_length: int = MAX_TEXT_INPUT_LENGTH) -> str:
    """
    Sanitizes user input to prevent prompt injection and token explosion.
    1. Truncates text exceeding maximum length.
    2. Neutralizes prompt injection directives.
    """
    if not text:
        return ""
        
    cleaned_text = text.strip()
    
    # Enforce token length ceiling
    if len(cleaned_text) > max_length:
        logger.warning(f"Input text truncated from {len(cleaned_text)} to {max_length} characters.")
        cleaned_text = cleaned_text[:max_length] + "... [truncated]"
        
    # Neutralize injection patterns by escaping special tokens
    for pattern in PROMPT_INJECTION_PATTERNS:
        if re.search(pattern, cleaned_text, re.IGNORECASE):
            logger.warning(f"Potential prompt injection pattern detected: {pattern}")
            cleaned_text = re.sub(pattern, "[FILTERED_INSTRUCTION]", cleaned_text, flags=re.IGNORECASE)
            
    return cleaned_text

def validate_pdf_file(file_obj_or_bytes, size_mb: Optional[float] = None, content_type: str = "application/pdf") -> Tuple[bool, Optional[str]]:
    """Validate PDF file size and type."""
    if not file_obj_or_bytes:
        return False, "No file uploaded"
        
    if size_mb is not None and size_mb > MAX_UPLOAD_SIZE_MB:
        return False, f"File size ({size_mb:.1f}MB) exceeds the {MAX_UPLOAD_SIZE_MB}MB limit"
        
    if content_type and "pdf" not in content_type.lower():
        return False, "Invalid file type. Please upload a PDF file"
        
    return True, None

def validate_pdf_content(text: str) -> Tuple[bool, Optional[str]]:
    """Validate if extracted text content contains medical indicators."""
    medical_terms = [
        'blood', 'test', 'report', 'laboratory', 'lab', 'patient', 'specimen',
        'reference range', 'analysis', 'results', 'medical', 'diagnostic',
        'hemoglobin', 'wbc', 'rbc', 'platelet', 'glucose', 'creatinine'
    ]
    
    if not text or len(text.strip()) < 50:
        return False, "Extracted text is too short. Please ensure the document contains valid text."
    
    text_lower = text.lower()
    term_matches = sum(1 for term in medical_terms if term in text_lower)
    
    if term_matches < 2:
        return False, "The document does not appear to contain standard medical terminology."
    
    return True, None

def validate_llm_output(output_text: str) -> str:
    """
    Validates and formats LLM model outputs:
    1. Ensures medical disclaimer is present.
    2. Fallbacks gracefully if empty.
    """
    if not output_text or not output_text.strip():
        return "> **Disclaimer**: Medical analysis could not be generated. Please consult a qualified healthcare provider."
        
    formatted = output_text.strip()
    
    # Ensure standard medical disclaimer is attached
    disclaimer = "> **Disclaimer**: This analysis is generated by AI and should not be considered a replacement for professional medical advice."
    if "disclaimer" not in formatted.lower():
        formatted = f"{disclaimer}\n\n{formatted}"
        
    return formatted
