import uuid
from typing import Any, Generic, List, Type, TypeVar, Union
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.base_class import Base

ModelType = TypeVar("ModelType", bound=Base)
CreateSchemaType = TypeVar("CreateSchemaType", bound=BaseModel)
UpdateSchemaType = TypeVar("UpdateSchemaType", bound=BaseModel)

class BaseRepository(Generic[ModelType, CreateSchemaType, UpdateSchemaType]):
    """
    Standard Asynchronous Repository pattern supplying default CRUD routines with soft delete support.
    """
    def __init__(self, model: Type[ModelType]):
        self.model = model

    async def get(self, db: AsyncSession, id: Any, include_deleted: bool = False) -> Union[ModelType, None]:
        """
        Fetch a single record by its primary key ID.
        """
        if isinstance(id, str):
            try:
                id = uuid.UUID(id)
            except ValueError:
                pass
                
        stmt = select(self.model).where(self.model.id == id)
        if not include_deleted and hasattr(self.model, "deleted_at"):
            stmt = stmt.where(self.model.deleted_at.is_(None))

        result = await db.execute(stmt)
        return result.scalars().first()

    async def get_multi(
        self, db: AsyncSession, *, skip: int = 0, limit: int = 100, include_deleted: bool = False
    ) -> List[ModelType]:
        """
        Fetch multiple records with offset and limit pagination.
        """
        stmt = select(self.model).offset(skip).limit(limit)
        if not include_deleted and hasattr(self.model, "deleted_at"):
            stmt = stmt.where(self.model.deleted_at.is_(None))

        result = await db.execute(stmt)
        return list(result.scalars().all())

    async def create(
        self, db: AsyncSession, *, obj_in: Union[CreateSchemaType, dict[str, Any]]
    ) -> ModelType:
        """
        Create a new database record from a Pydantic schema or a plain dict.

        Accepts a dict for the same reason `update` already does: several models
        (reports, notifications) are written from assembled server-side values
        that have no request schema of their own.
        """
        obj_in_data = obj_in if isinstance(obj_in, dict) else obj_in.model_dump()
        db_obj = self.model(**obj_in_data)
        db.add(db_obj)
        await db.flush()  # Populates autogenerated fields (like id/timestamps)
        return db_obj

    async def update(
        self,
        db: AsyncSession,
        *,
        db_obj: ModelType,
        obj_in: Union[UpdateSchemaType, dict[str, Any]]
    ) -> ModelType:
        """
        Update an existing database record.
        """
        if isinstance(obj_in, dict):
            update_data = obj_in
        else:
            update_data = obj_in.model_dump(exclude_unset=True)
            
        for field, value in update_data.items():
            if hasattr(db_obj, field):
                setattr(db_obj, field, value)
                
        db.add(db_obj)
        await db.flush()
        return db_obj

    async def remove(self, db: AsyncSession, *, id: Any) -> Union[ModelType, None]:
        """
        Permanently delete a database record by its ID.
        """
        db_obj = await self.get(db, id, include_deleted=True)
        if db_obj:
            await db.delete(db_obj)
            await db.flush()
        return db_obj

    async def soft_remove(self, db: AsyncSession, *, id: Any) -> Union[ModelType, None]:
        """
        Soft delete a database record by populating deleted_at timestamp.
        """
        db_obj = await self.get(db, id)
        if db_obj:
            db_obj.soft_delete()
            db.add(db_obj)
            await db.flush()
        return db_obj
